### ISSUE TITLE
last_reset must not be an int

### ISSUE THREAD

**Issue by mptei** [CJNE/ha-sunspec#31]
## Version of the custom_component
0.0.7

## Describe the bug
If "last_reset" is set to an int, the event processing for the StatisticsTasks throws an error.

## Debug log

```text

2021-08-11 18:17:36 ERROR (Recorder) [homeassistant.components.recorder] Error while processing event StatisticsTask(start=datetime.datetime(2021, 8, 11, 15, 0, tzinfo=datetime.timezone.ut\
c)): argument 1 must be str, not int
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 623, in _run_event_loop
    self._process_one_event_or_recover(event)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 632, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 738, in _process_one_event
    self._run_statistics(event.start)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/__init__.py", line 721, in _run_statistics
    if statistics.compile_statistics(self, start):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/util.py", line 303, in wrapper
    return job(instance, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/recorder/statistics.py", line 154, in compile_statistics
    platform_stats.append(platform.compile_statistics(instance.hass, start, end))
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/sensor/recorder.py", line 284, in compile_statistics
    stat["last_reset"] = dt_util.parse_datetime(last_reset)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/util/dt.py", line 133, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not int

```

The problem seems to be here: https://github.com/CJNE/ha-sunspec/blob/a81faf6607adc9d1fb7149cf6f3caee37c4b817a/custom_components/sunspec/sensor.py#L208

this should be changed to 
```
dt.utc_from_timestamp(0)
```
where dt is
```
from homeassistant.util import dt
```

**Comment by CJNE** [comment]
Thanks guys, i have merged and released this in 0.0.8!
